{"lesson":{"id":2443,"name":"Raising Exceptions","type":0,"mode":1,"videoID":null,"tags":"exceptions","quizzes":[{"id":5044,"number":1,"videoStart":0.0,"videoEnd":0.0,"linkedVideoID":null,"type":1,"linkedQuizID":null,"tip":null,"hint":null,"time":0,"answers":[{"id":98099,"text":"ZeroDivisionError","isCorrect":false,"properties":{}},{"id":98100,"text":"ValueError","isCorrect":false,"properties":{}},{"id":98101,"text":"ZeroDivisionError and ValueError","isCorrect":true,"properties":{}},{"id":98102,"text":"none","isCorrect":false,"properties":{}}],"question":"Which errors occur in this code?\r\ntry:\r\n  print(1 / 0)\r\nexcept ZeroDivisionError:\r\n  raise ValueError","textContent":"[h1]Raising Exceptions[/h1]\r\n\r\nYou can raise exceptions by using the [b]raise [/b]statement.  [code format=\"py\" codeId=\"349\"]print(1)\r\n[b]raise ValueError[/b]\r\nprint(2)[/code]\r\n[b]Result:[/b][code format=\"raw\" ]>>>\r\n1\r\nValueError\r\n>>>[/code]\r\n[note]You need to specify the [b]type [/b]of the exception raised.[/note]"},{"id":5045,"number":2,"videoStart":0.0,"videoEnd":0.0,"linkedVideoID":null,"type":3,"linkedQuizID":null,"tip":null,"hint":null,"time":0,"answers":[{"id":104430,"text":"<","isCorrect":false,"properties":{"prefix":"","postfix":""}},{"id":104431,"text":"raise","isCorrect":false,"properties":{"prefix":"","postfix":""}}],"question":"Fill in the blanks to raise a ValueError exception, if the input is negative.\r\n[!raw!]\r\nnum = input(\":\")\r\nif float(num) {0} 0:\r\n  {1} ValueError(\"Negative!\")","textContent":"[h1]Raising Exceptions[/h1]\r\n\r\nExceptions can be raised with arguments that give detail about them.\r\n[b]For example:[/b] [code format=\"py\" codeId=\"350\"]name = \"123\"\r\n[b]raise [/b]NameError(\"Invalid name!\")[/code]\r\n[b]Result:[/b] [code format=\"raw\" ]>>>\r\nNameError: Invalid name!\r\n>>>[/code]"},{"id":5046,"number":3,"videoStart":0.0,"videoEnd":0.0,"linkedVideoID":null,"type":1,"linkedQuizID":null,"tip":null,"hint":null,"time":0,"answers":[{"id":98105,"text":"Yes","isCorrect":true,"properties":{}},{"id":98106,"text":"No","isCorrect":false,"properties":{}}],"question":"Can you use the raise statement outside the except block?","textContent":"[h1]Raising Exceptions[/h1]\r\n\r\nIn [b]except [/b]blocks, the [b]raise [/b]statement can be used without arguments to re-raise whatever exception occurred.\r\n[b]For example:[/b] [code format=\"py\" codeId=\"351\"]try:\r\n   num = 5 / 0\r\nexcept:\r\n   print(\"An error occurred\")\r\n   [b]raise[/b][/code]\r\n[b]Result:[/b][code format=\"raw\" ]>>>\r\nAn error occurred\r\n\r\nZeroDivisionError: division by zero\r\n>>>[/code]"}]}}