{"lesson":{"id":2442,"name":"finally","type":0,"mode":1,"videoID":null,"tags":"exceptions","quizzes":[{"id":5042,"number":1,"videoStart":0.0,"videoEnd":0.0,"linkedVideoID":null,"type":1,"linkedQuizID":null,"tip":null,"hint":null,"time":0,"answers":[{"id":98092,"text":"1   3","isCorrect":true,"properties":{}},{"id":98093,"text":"1   2   3","isCorrect":false,"properties":{}},{"id":98094,"text":"1","isCorrect":false,"properties":{}},{"id":98095,"text":"3","isCorrect":false,"properties":{}}],"question":"What is the output of this code?\r\ntry:\r\n  print(1)\r\nexcept:\r\n  print(2)\r\nfinally:\r\n  print(3)","textContent":"[h1]finally[/h1]\r\n\r\nTo ensure some code runs no matter what errors occur, you can use a [b]finally[/b] statement. The [b]finally [/b]statement is placed at the bottom of a [b]try/except[/b] statement. Code within a [b]finally [/b]statement always runs after execution of the code in the [b]try[/b], and possibly in the [b]except[/b], blocks.[code format=\"py\" codeId=\"347\"]try:\r\n   print(\"Hello\")\r\n   print(1 / 0)\r\nexcept ZeroDivisionError:\r\n   print(\"Divided by zero\")\r\n[b]finally:[/b]\r\n   print(\"This code will run no matter what\")[/code]\r\n[b]Result:[/b][code format=\"raw\" ]>>>\r\nHello\r\nDivided by zero\r\nThis code will run no matter what\r\n>>>[/code]"},{"id":5043,"number":2,"videoStart":0.0,"videoEnd":0.0,"linkedVideoID":null,"type":6,"linkedQuizID":null,"tip":null,"hint":null,"time":0,"answers":[{"id":98096,"text":"try:","isCorrect":true,"properties":{}},{"id":98097,"text":"except:","isCorrect":true,"properties":{}},{"id":98098,"text":"finally:","isCorrect":true,"properties":{}}],"question":"Fill in the blanks to create a try/except/finally block.\r\n[!raw!]\r\n{0}\r\n  print(1)\r\n{1}\r\n  print(2)\r\n{2}\r\n  print(42)","textContent":"[h1]finally[/h1]\r\n\r\nCode in a [b]finally [/b]statement even runs if an uncaught exception occurs in one of the preceding blocks. [code format=\"py\" codeId=\"348\"]try:\r\n   print(1)\r\n   print(10 / 0)\r\nexcept ZeroDivisionError:\r\n   print(unknown_var)\r\nfinally:\r\n   print(\"This is executed last\")[/code]\r\n[b]Result:[/b] [code format=\"raw\" ]>>>\r\n1\r\nThis is executed last\r\n\r\nZeroDivisionError: division by zero\r\nDuring handling of the above exception, another exception occurred:\r\nNameError: name 'unknown_var' is not defined\r\n>>>[/code]"}]}}